### ISSUE TITLE
TypeError: _.forEach is not a function

### ISSUE THREAD

**Issue by adamcoulombe** [sgamon/lodash-express#2]
Not sure if this is an issue with `lodash-express` or with `lodash.template`, but my template looks like:
```
  <ul>
  	<% _.forEach(posts, function(post) { %>
  		<li><%= post.title %></li>
  	<% }); %>
  </ul>
```
and I get:
```
 _.forEach(posts, function(post) { ;
   ^

TypeError: _.forEach is not a function
    at eval (eval at <anonymous> (D:\postapp\node_modules\lodash
-express\node_modules\lodash.template\index.js:1089:12), <anonymous>
:13:4)
    at D:\postapp\node_modules\lodash-express\lodash-express.js:
36:20
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by sgamon** [comment]
lodash-express uses the minimal template module (lodash.template), not the full lodash build. Therefore, lodash is not "built in" to the template engine.

However, you can pass lodash into the template from the controller:

    let _ = require('lodash');
    res.render('posts', {_:_, posts:posts});

**Comment by adamcoulombe** [comment]
Pull request to add these instuctions to readme #3

**Comment by AdarshK15** [comment]
use _.forEach() not _.foreach and if you are using ejs make sure you gave appropriate spaces between the <% %> tags
